Disable typechecking in CI.
The typecheck was failing with this error, but I didn't want to spend
time fixing it now:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/bin/black", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/black.py", line 352, in main
    executor=executor,
  File "/opt/python/3.7-dev/lib/python3.7/asyncio/base_events.py", line 495, in run_until_complete
    return future.result()
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/black.py", line 462, in schedule_formatting
    src = tasks.pop(task)
KeyError: <Task finished coro=<BaseEventLoop.run_in_executor() done, defined at /opt/python/3.7-dev/lib/python3.7/asyncio/base_events.py:653> result=False>
```

It may be because travis is using an odd version of Python 3.7, but I am
not sure.